Made scripts allStart, allStop, allCheck to be startable from everywhere
git-svn-id: https://svnsrv.desy.de/desy/EuXFEL/WP76/karabo/karaboFramework/branches/1.3@17111 a23ab9f9-1ea2-4934-960d-990259f9ea8c

diff --git a/run/bin/allStart b/run/bin/allStart
--- a/run/bin/allStart
+++ b/run/bin/allStart
@@ -4,6 +4,14 @@
 # additional information (including arguements) are described in ./allInfo
 # author: CY 18.12.2012
 
+# Make sure the script runs in this directory
+scriptDir=$(dirname `[[ $0 = /* ]] && echo "$0" || echo "$PWD/${0#./}"`)
+cd ${scriptDir}
+if [ $? -ne 0 ]; then
+    echo "ERROR Could not change directory to ${scriptDir}"
+    exit 1;
+fi
+
 # check startup
 ./allCheck
 check=$?
diff --git a/run/bin/allStop b/run/bin/allStop
--- a/run/bin/allStop
+++ b/run/bin/allStop
@@ -1,5 +1,13 @@
 #! /bin/bash
 
+# Make sure the script runs in this directory
+scriptDir=$(dirname `[[ $0 = /* ]] && echo "$0" || echo "$PWD/${0#./}"`)
+cd ${scriptDir}
+if [ $? -ne 0 ]; then
+    echo "ERROR Could not change directory to ${scriptDir}"
+    exit 1;
+fi
+
 source ./allInfo
 
 while read line; do
