This fixes overwriting of the config file.
- A new directory 'var/config' was created where the user's config file is placed
- Only the template config.orig will be overwritten by fresh installations
- Additionally shortened the start-up time for xterms

diff --git a/src/tools/scripts/karabo-check b/src/tools/scripts/karabo-check
--- a/src/tools/scripts/karabo-check
+++ b/src/tools/scripts/karabo-check
@@ -3,14 +3,6 @@
 # karabo-check checks the correctness of the definitions contained in config
 # author: CY 18.12.2012
 
-# Make sure the script runs in this directory
-scriptDir=$(dirname `[[ $0 = /* ]] && echo "$0" || echo "$PWD/${0#./}"`)
-cd ${scriptDir}
-if [ $? -ne 0 ]; then
-    echo "ERROR Could not change directory to ${scriptDir}"
-    exit 1;
-fi
-
 # Make sure Karabo is installed
 if [ -z $KARABO ]; then
   echo
@@ -18,8 +10,16 @@ if [ -z $KARABO ]; then
   exit 1
 fi
 
+# Make sure the script runs in $KARABO/var/config
+scriptDir=$KARABO/var/config
+cd ${scriptDir}
+if [ $? -ne 0 ]; then
+    echo "ERROR Could not change directory to ${scriptDir}"
+    exit 1;
+fi
+
 if [ ! -e "config" ]; then
-    cp config.orig config
+    cp $KARABO/bin/config.orig config
 fi
 
 # returns the number of xterms running and cleans up if there are none
