add protections in ./karabo script:
plugins directory of servers does not exist after git checkout

diff --git a/run/karabo b/run/karabo
--- a/run/karabo
+++ b/run/karabo
@@ -1235,7 +1235,13 @@ function buildPackage() {
 	make -j${numMakeThreads} CONF=$buildType
 	# link only when library.so file exist otherwise explicit '*/*' link created
 	if [ $? -eq 0 ]; then
-	    cd $scriptDir/servers/cppDeviceServer/plugins
+            # pluginDir should exist - but not in case of a fresh git checkout
+            pluginDir=$scriptDir/servers/cppDeviceServer/plugins
+            if ! mkdir -p $pluginDir ; then  # create if not yet there
+                echo "ERROR: Cannot create directory '$pluginDir': Is there a file?" >&2
+                return 1
+            fi
+            cd $pluginDir
 	    find $scriptDir/packages/$cat/$pck/dist/$buildType -type f \( -name \*.so -or -name \*.dylib \) -exec ln -sf {} \;
             if [ $? -ne 0 ]; then
                 # failure of making the link FIXME: what if no .so exists?
@@ -1245,7 +1251,13 @@ function buildPackage() {
             return 1  # failure of make
 	fi
     else
-	cd $scriptDir/servers/pythonDeviceServer/plugins
+        # pluginDir should exist - but not in case of a fresh git checkout
+        pluginDir=$scriptDir/servers/pythonDeviceServer/plugins
+        if ! mkdir -p $pluginDir ; then  # create if not yet there
+            echo "ERROR: Cannot create directory '$pluginDir': Is there a file?" >&2
+            return 1
+        fi
+	cd $pluginDir
 	find $scriptDir/packages/$cat/$pck/src -maxdepth 1 -type f -not -name main.py -name \*.py -exec grep -q 'class.*(.*Python.*Device' {} \; -exec ln -sf {} \;
         if [ $? -ne 0 ]; then
             return 1  # failure of making the link FIXME: what if no .py exists?
@@ -1372,9 +1384,21 @@ function installPlugin () {
     popd
 
     if [ `find $binInstallDir/$pluginName-$pluginVersion-${VERSION} -maxdepth 1 -type f -name \*.so` ]; then
-        ( cd $scriptDir/servers/cppDeviceServer/plugins; find $binInstallDir/$pluginName-$pluginVersion-${VERSION} -maxdepth 1  -type f -name \*.so -exec ln -sf {} \; )
+        # pluginDir should exist - but not in case of a fresh git checkout
+        pluginDir=$scriptDir/servers/cppDeviceServer/plugins
+        if ! mkdir -p $pluginDir ; then  # create if not yet there
+            echo "ERROR: Cannot create directory '$pluginDir': Is there a file?" >&2
+            return 1
+        fi
+        ( cd $pluginDir; find $binInstallDir/$pluginName-$pluginVersion-${VERSION} -maxdepth 1  -type f -name \*.so -exec ln -sf {} \; )
     elif [ `find $binInstallDir/$pluginName-$pluginVersion-${VERSION} -maxdepth 1 -type f -name \*.py` ]; then
-        ( cd $scriptDir/servers/pythonDeviceServer/plugins; find $binInstallDir/$pluginName-$pluginVersion-${VERSION} -maxdepth 1 -type f -not -name main.py -name \*.py -exec grep -q 'class.*(.*Python.*Device' {} \; -exec ln -sf {} \; )
+        # pluginDir should exist - but not in case of a fresh git checkout
+        pluginDir=$scriptDir/servers/pythonDeviceServer/plugins
+        if ! mkdir -p $pluginDir ; then  # create if not yet there
+            echo "ERROR: Cannot create directory '$pluginDir': Is there a file?" >&2
+            return 1
+        fi
+        ( cd $pluginDir; find $binInstallDir/$pluginName-$pluginVersion-${VERSION} -maxdepth 1 -type f -not -name main.py -name \*.py -exec grep -q 'class.*(.*Python.*Device' {} \; -exec ln -sf {} \; )
     fi
     dependsPath=$binInstallDir/$pluginName-$pluginVersion-${VERSION}/DEPENDS
 
