'./karabo rebuild' now returns success or failure
Note: failures with dependencies or missing .so/.py files are not caught

diff --git a/run/karabo b/run/karabo
--- a/run/karabo
+++ b/run/karabo
@@ -1107,7 +1107,8 @@ function updateInstalled() {
 
 
 
-# Rebuild all packages in a given configuration
+# Rebuild all packages in a given configuration.
+# Returns non-zero if any package build fails.
 # @param $1 buildType [Release|Debug]
 # @param $2 force [force,canSkip]
 # @param $3 packageName ("" if not provided)
@@ -1118,8 +1119,10 @@ function rebuildInstalled() {
     
     if [[ "$3" != "" ]]; then
 	buildPackage $3 $4 $buildType $force
-	return
+	return $?
     fi
+
+    local -i returnStatus=0
 
     cd $scriptDir/packages
     
@@ -1147,15 +1150,20 @@ function rebuildInstalled() {
 	    #local packagePath=$scriptDir/packages/$cat/$pck
 
 	    buildPackage $pck $cat $buildType $force        
+            if [ $? -ne 0 ]; then
+                returnStatus=1
+            fi
 
 	    cd $categoryPath
 	    
 	done
         cd $scriptDir/packages
     done
-	    
+    return $returnStatus
 }
 
+# Builds a package as defined by parameters.
+# Returns non-zero if any package build fails.
 # @param $1 package
 # @param $2 category
 # @param $3 buildType [Release|Debug]
@@ -1187,6 +1195,8 @@ function buildPackage() {
     fi
     
     
+    # FIXME:
+    # For now we ignore failure with dependencies below for return value!
     local idy=0
     while [ $idy -lt $depsNumberOfElements ]; do
 	let "categoryIdy = $idy + 1"
@@ -1214,6 +1224,7 @@ function buildPackage() {
 	let "idy = $idy + 4"
     done
     
+    local -i returnValue=0
     ### Build package itself
     
     cd $packagePath
@@ -1226,11 +1237,21 @@ function buildPackage() {
 	if [ $? -eq 0 ]; then
 	    cd $scriptDir/servers/cppDeviceServer/plugins
 	    find $scriptDir/packages/$cat/$pck/dist/$buildType -type f \( -name \*.so -or -name \*.dylib \) -exec ln -sf {} \;
+            if [ $? -ne 0 ]; then
+                # failure of making the link FIXME: what if no .so exists?
+                return 1
+            fi
+        else
+            return 1  # failure of make
 	fi
     else
 	cd $scriptDir/servers/pythonDeviceServer/plugins
 	find $scriptDir/packages/$cat/$pck/src -maxdepth 1 -type f -not -name main.py -name \*.py -exec grep -q 'class.*(.*Python.*Device' {} \; -exec ln -sf {} \;
-    fi    
+        if [ $? -ne 0 ]; then
+            return 1  # failure of making the link FIXME: what if no .py exists?
+        fi
+    fi
+    return 0  # looks like success...
 }
 
 
